# 对外暴露的http端口号
port=9000
# 是什么环境
env="dev"

# 日志类型，文件：file，终端：stdout，系统日志：syslog
logtype = "file"

# 日志等级
loglevel = 1

# etcd的配置
[op]
    # etcd集群的地址
    endpoints      = ["127.0.0.1:2379"]
    # 注册的prefix
    prefix         = "/main/dev"
    # 注册的服务名称
    server_name    = "api.Api"
    # 监听的服务名称
    watch_servers  = ["passport.Passport","user.User","msg.Msg","file.File","id.Id"]


[log]
    # 文件名称
    filename       = "api_gateway"
    # 文件数量
    filenum        = 50
    # 文件大小Mb
    filesize       = 256
    # 日志的输出文件夹
    dir            = "/srv/api_gateway/logs"
    #  是否开启gzip压缩
    use_gzip       = true